name: EpicZones
main: com.epicsagaonline.bukkit.EpicZones.EpicZones
version: 0.17
website: http://code.google.com/p/team-eso/
author: jblaske@gmail.com
description: >
             Provides polygon based protection for your bukkit server.
commands:
  zone:
    description: Houses all of the commands for EpicZones.
    usage: |
           /<command> <subcommand> [Value] [Value] [Value]
           Example: /<command> create [tag] - Creates a new zone with the provided tag.
  reloadez:
    aliases: reload
    description: Reloads all of EpicZones configuration settings.
    usage: |
           /<command>
           Example: /<command> - Reloads EpicZones.
  who:
    aliases: [who, online, whois]
    description: Provides a list of players that are on the server.
    usage: |
           /<command> [all]
           Example: /<command> - Lists all players in your current zone.
           Example: /<command> all - Lists all players on the server and shows what zone they are in.